import { part1 } from './1';
import { part2 } from './2';
import { part3 } from './3';
import { part4 } from './4';
import { part5 } from './5';
import { part6 } from './6';
import { part7 } from './7';
import { part8 } from './8';
import { part9 } from './9';
import { part10 } from './10';
import { part11 } from './11';
import { part12 } from './12';

// part1();
// part2();
// part3();
// part4();
// part5();
// part6();
// part7();
// part8();
// part9();
// part10();
// part11();
part12();
